### PR TITLE
Allow for use without JQuery

### PR DESCRIPTION
**Pull request by MikaAK**
Quick fix to allow for use without jquery

### CODE REVIEW

**Comment by cgwyllie** [comment]
Hi @MikaAK, thanks for submitting a pull for this!

Having had a quick look over the file, there are a few other usages of jQuery/the jQuery syntax that we'd need to iron out. Here are my thoughts:

1. Make a new variable, `Velocity`, in the top of the anonymous function wrapper
1. Assign the global Velocity object to it with your condition like `var Velocity = window.Velocity || $.Velocity;`
1. Make your patch's lines 13 & 214 use the new `Velocity` variable
1. Replace all `$el.velocity` calls with Velocity [utility function](http://julian.com/research/velocity/#utilityFunction) calls such as `Velocity($el[0], ...)`
1. Replace the jQuery call on [line 158](https://github.com/cgwyllie/angular-velocity/blob/master/angular-velocity.js#L158) with the utility function too

How does that sound?

Happy to discuss further or to help make the changes, whichever works for you :)

Thanks!
  Chris

**Comment by MikaAK** [comment]
Hey thanks for letting me know about the missed points. 

I'll update the PR to use `var Velocity = window.Velocity || (window.$ && $.Velocity);` I was previously getting errors that $ wasn't defined so this is a fair fix.

As the the call replacements I'll submit those as well though its worth noting they work directly on an angular.element so we shouldn't need to add the `[0]` part!

Cheers,
Mika

**Comment by cgwyllie** [comment]
Great! Yep, fair point about the missing `$` reference, had not thought of that!

Interesting that the Velocity calls work on the angular element as well, I wonder if the util function unwraps them internally...

Let me know once you're happy for me to test, merge, update :)

Thanks,
Chris

**Comment by MikaAK** [comment]
It should be ready :)

**Comment by cgwyllie** [comment]
Sweet, hopefully get it all merged in soon!

**Comment by cgwyllie** [comment]
Released as 0.2.5, only slight change was using `jQuery` instead of `$` to allow for no conflicts mode.

Thanks again for submitting this!

**Pull request merged**
